const express=require("express")
const router=express.Router()
const {signUp,loginUser,userProfile,updateUser,deleteUser}=require("../controllers/authController.js")
const auth=require("../middleware/authMiddleware.js")
router.post("/signup",signUp)
router.post("/loginuser",loginUser)
router.get("/profile",auth,userProfile)
router.put("/upadteuser",auth,updateUser)
router.delete("/deleteuser",auth,deleteUser)
module.exports=router